### ISSUE TITLE
rephand does not repair

### ISSUE THREAD

**Issue by Git-Forked** [enchant97/minetest_simple_commands#1]
Anvil will repair but /rephand will not.

Expected result:  tool is fully repaired.

Actual result: nothing happens.

### **Minetest server info:** 
```
Minetest 5.4.0 (Linux)
Using Irrlicht 1.8.4
Using Lua 5.1.5
BUILD_TYPE=Release
RUN_IN_PLACE=0
USE_CURL=1
USE_GETTEXT=0
USE_SOUND=1
USE_FREETYPE=1
```

**Comment by enchant97** [comment]
@BugReportering I'll look into it

**Comment by Git-Forked** [comment]
Thanks for the quick fix.
